defaults: &defaults
  admin: # used only during seeding!
    username: brewster
    email: brewster1134@gmail.com
    password: password
  currency: USD
  email:
    no_reply: noreply@example.com
    interceptor: brewster1134@gmail.com
  host: 'localhost:3000'
  title: Artist Manager

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: 'domain.com'