defaults: &defaults
  admin: # used only during seeding!
    email: brewster1134@gmail.com
    username: brewster
    password: password
  currency: USD
  google:
    email: brewster1134@gmail.com
    password: axutryvszciecqws
    calendar:
      name: Events
  email:

    # For development only.  All emails sent while developing will be sent to this email. 
    interceptor: brewster1134@gmail.com

    # Emails sent from the site that you do not want to be replied to, will be sent from this email.
    no_reply: noreply@example.com

  # Most important is to set this below for production.
  host: 'localhost:3000'
  
  # Default title shown in the browser tab
  title: Artist Manager
  splash_page: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: 'domain.com'